//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyMedico
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    public partial class MedicoDC : object
    {
        
        private string ApeMedicoField;
        
        private string ApeNomMedicoField;
        
        private string CodEspecialidadField;
        
        private string CodMedicoField;
        
        private string DirecMedicoField;
        
        private string DniMedicoField;
        
        private int EdadField;
        
        private string EmailMedicoField;
        
        private string EspecialidadField;
        
        private int Est_MedicoField;
        
        private string EstadoField;
        
        private System.DateTime FecIngresoField;
        
        private System.DateTime FecNacMedicoField;
        
        private System.DateTime FecRegistroField;
        
        private System.DateTime FecUltModField;
        
        private string IdUbigeoField;
        
        private string LoginUsuarioField;
        
        private string NomMedicoField;
        
        private string UsuRegistroField;
        
        private string UsuUltModField;
        
        private string departamentoField;
        
        private string distritoField;
        
        private string numColegiaturaField;
        
        private string provinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMedico
        {
            get
            {
                return this.ApeMedicoField;
            }
            set
            {
                this.ApeMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomMedico
        {
            get
            {
                return this.ApeNomMedicoField;
            }
            set
            {
                this.ApeNomMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEspecialidad
        {
            get
            {
                return this.CodEspecialidadField;
            }
            set
            {
                this.CodEspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMedico
        {
            get
            {
                return this.CodMedicoField;
            }
            set
            {
                this.CodMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecMedico
        {
            get
            {
                return this.DirecMedicoField;
            }
            set
            {
                this.DirecMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniMedico
        {
            get
            {
                return this.DniMedicoField;
            }
            set
            {
                this.DniMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailMedico
        {
            get
            {
                return this.EmailMedicoField;
            }
            set
            {
                this.EmailMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad
        {
            get
            {
                return this.EspecialidadField;
            }
            set
            {
                this.EspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Medico
        {
            get
            {
                return this.Est_MedicoField;
            }
            set
            {
                this.Est_MedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso
        {
            get
            {
                return this.FecIngresoField;
            }
            set
            {
                this.FecIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNacMedico
        {
            get
            {
                return this.FecNacMedicoField;
            }
            set
            {
                this.FecNacMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro
        {
            get
            {
                return this.FecRegistroField;
            }
            set
            {
                this.FecRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecUltMod
        {
            get
            {
                return this.FecUltModField;
            }
            set
            {
                this.FecUltModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo
        {
            get
            {
                return this.IdUbigeoField;
            }
            set
            {
                this.IdUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginUsuario
        {
            get
            {
                return this.LoginUsuarioField;
            }
            set
            {
                this.LoginUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMedico
        {
            get
            {
                return this.NomMedicoField;
            }
            set
            {
                this.NomMedicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuRegistro
        {
            get
            {
                return this.UsuRegistroField;
            }
            set
            {
                this.UsuRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuUltMod
        {
            get
            {
                return this.UsuUltModField;
            }
            set
            {
                this.UsuUltModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito
        {
            get
            {
                return this.distritoField;
            }
            set
            {
                this.distritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numColegiatura
        {
            get
            {
                return this.numColegiaturaField;
            }
            set
            {
                this.numColegiaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMedico.IServicioMedico")]
    public interface IServicioMedico
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ListarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ListarMedicoResponse")]
        System.Collections.Generic.List<ProxyMedico.MedicoDC> usp_ListarMedico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ListarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ListarMedicoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMedico.MedicoDC>> usp_ListarMedicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_InsertarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_InsertarMedicoResponse")]
        bool usp_InsertarMedico(ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_InsertarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_InsertarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarMedicoAsync(ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ActualizarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ActualizarMedicoResponse")]
        bool usp_ActualizarMedico(ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ActualizarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ActualizarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarMedicoAsync(ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_EliminarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_EliminarMedicoResponse")]
        bool usp_EliminarMedico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_EliminarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_EliminarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarMedicoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ConsultarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ConsultarMedicoResponse")]
        ProxyMedico.MedicoDC usp_ConsultarMedico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ConsultarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ConsultarMedicoResponse")]
        System.Threading.Tasks.Task<ProxyMedico.MedicoDC> usp_ConsultarMedicoAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioMedicoChannel : ProxyMedico.IServicioMedico, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioMedicoClient : System.ServiceModel.ClientBase<ProxyMedico.IServicioMedico>, ProxyMedico.IServicioMedico
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioMedicoClient() : 
                base(ServicioMedicoClient.GetDefaultBinding(), ServicioMedicoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioMedico.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMedicoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioMedicoClient.GetBindingForEndpoint(endpointConfiguration), ServicioMedicoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMedicoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioMedicoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMedicoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioMedicoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioMedicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyMedico.MedicoDC> usp_ListarMedico()
        {
            return base.Channel.usp_ListarMedico();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyMedico.MedicoDC>> usp_ListarMedicoAsync()
        {
            return base.Channel.usp_ListarMedicoAsync();
        }
        
        public bool usp_InsertarMedico(ProxyMedico.MedicoDC objMedicoDC)
        {
            return base.Channel.usp_InsertarMedico(objMedicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarMedicoAsync(ProxyMedico.MedicoDC objMedicoDC)
        {
            return base.Channel.usp_InsertarMedicoAsync(objMedicoDC);
        }
        
        public bool usp_ActualizarMedico(ProxyMedico.MedicoDC objMedicoDC)
        {
            return base.Channel.usp_ActualizarMedico(objMedicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarMedicoAsync(ProxyMedico.MedicoDC objMedicoDC)
        {
            return base.Channel.usp_ActualizarMedicoAsync(objMedicoDC);
        }
        
        public bool usp_EliminarMedico(string strCodigo)
        {
            return base.Channel.usp_EliminarMedico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarMedicoAsync(string strCodigo)
        {
            return base.Channel.usp_EliminarMedicoAsync(strCodigo);
        }
        
        public ProxyMedico.MedicoDC usp_ConsultarMedico(string strCodigo)
        {
            return base.Channel.usp_ConsultarMedico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyMedico.MedicoDC> usp_ConsultarMedicoAsync(string strCodigo)
        {
            return base.Channel.usp_ConsultarMedicoAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMedico))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioMedico))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_CheckSalud/ServicioMedico/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioMedicoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioMedico);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioMedicoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioMedico);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioMedico,
        }
    }
}
