//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyEnfermedad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnfermedadDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class EnfermedadDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEnfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descEnfermedadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEnfermedad {
            get {
                return this.codEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.codEnfermedadField, value) != true)) {
                    this.codEnfermedadField = value;
                    this.RaisePropertyChanged("codEnfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descEnfermedad {
            get {
                return this.descEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.descEnfermedadField, value) != true)) {
                    this.descEnfermedadField = value;
                    this.RaisePropertyChanged("descEnfermedad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEnfermedad.IServicioEnfermedad")]
    public interface IServicioEnfermedad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEnfermedad/ListarEnfermedad", ReplyAction="http://tempuri.org/IServicioEnfermedad/ListarEnfermedadResponse")]
        TestWeb_WCF_CheckSalud.ProxyEnfermedad.EnfermedadDC[] ListarEnfermedad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEnfermedad/ListarEnfermedad", ReplyAction="http://tempuri.org/IServicioEnfermedad/ListarEnfermedadResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEnfermedad.EnfermedadDC[]> ListarEnfermedadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEnfermedadChannel : TestWeb_WCF_CheckSalud.ProxyEnfermedad.IServicioEnfermedad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEnfermedadClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyEnfermedad.IServicioEnfermedad>, TestWeb_WCF_CheckSalud.ProxyEnfermedad.IServicioEnfermedad {
        
        public ServicioEnfermedadClient() {
        }
        
        public ServicioEnfermedadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEnfermedadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEnfermedadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEnfermedadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyEnfermedad.EnfermedadDC[] ListarEnfermedad() {
            return base.Channel.ListarEnfermedad();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEnfermedad.EnfermedadDC[]> ListarEnfermedadAsync() {
            return base.Channel.ListarEnfermedadAsync();
        }
    }
}
