//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyConsultas
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultConsultas", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    public partial class ResultConsultas : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string NomMedicoField;
        
        private string NomPacienteField;
        
        private string codConsultaField;
        
        private string codMedicoField;
        
        private string codPacienteField;
        
        private string especialidadMedicoField;
        
        private string estadoConsultaField;
        
        private System.DateTime fechConsultaField;
        
        private string motivoConsultaField;
        
        private string resultadoConsultaField;
        
        private int totalConsultasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMedico
        {
            get
            {
                return this.NomMedicoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomMedicoField, value) != true))
                {
                    this.NomMedicoField = value;
                    this.RaisePropertyChanged("NomMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPaciente
        {
            get
            {
                return this.NomPacienteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPacienteField, value) != true))
                {
                    this.NomPacienteField = value;
                    this.RaisePropertyChanged("NomPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codConsulta
        {
            get
            {
                return this.codConsultaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.codConsultaField, value) != true))
                {
                    this.codConsultaField = value;
                    this.RaisePropertyChanged("codConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codMedico
        {
            get
            {
                return this.codMedicoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.codMedicoField, value) != true))
                {
                    this.codMedicoField = value;
                    this.RaisePropertyChanged("codMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPaciente
        {
            get
            {
                return this.codPacienteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.codPacienteField, value) != true))
                {
                    this.codPacienteField = value;
                    this.RaisePropertyChanged("codPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string especialidadMedico
        {
            get
            {
                return this.especialidadMedicoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.especialidadMedicoField, value) != true))
                {
                    this.especialidadMedicoField = value;
                    this.RaisePropertyChanged("especialidadMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoConsulta
        {
            get
            {
                return this.estadoConsultaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.estadoConsultaField, value) != true))
                {
                    this.estadoConsultaField = value;
                    this.RaisePropertyChanged("estadoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechConsulta
        {
            get
            {
                return this.fechConsultaField;
            }
            set
            {
                if ((this.fechConsultaField.Equals(value) != true))
                {
                    this.fechConsultaField = value;
                    this.RaisePropertyChanged("fechConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string motivoConsulta
        {
            get
            {
                return this.motivoConsultaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.motivoConsultaField, value) != true))
                {
                    this.motivoConsultaField = value;
                    this.RaisePropertyChanged("motivoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultadoConsulta
        {
            get
            {
                return this.resultadoConsultaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.resultadoConsultaField, value) != true))
                {
                    this.resultadoConsultaField = value;
                    this.RaisePropertyChanged("resultadoConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalConsultas
        {
            get
            {
                return this.totalConsultasField;
            }
            set
            {
                if ((this.totalConsultasField.Equals(value) != true))
                {
                    this.totalConsultasField = value;
                    this.RaisePropertyChanged("totalConsultas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultas.IServicioConsultas")]
    public interface IServicioConsultas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_VerConsultasPendientes", ReplyAction="http://tempuri.org/IServicioConsultas/sp_VerConsultasPendientesResponse")]
        System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_VerConsultasPendientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_VerConsultasPendientes", ReplyAction="http://tempuri.org/IServicioConsultas/sp_VerConsultasPendientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_VerConsultasPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ListarConsultasPaciente", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ListarConsultasPacienteResponse")]
        System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ListarConsultasPaciente(string strCodigo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ListarConsultasPaciente", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ListarConsultasPacienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ListarConsultasPacienteAsync(string strCodigo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ConsultasAsignadasMedico", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ConsultasAsignadasMedicoResponse")]
        System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ConsultasAsignadasMedico(string strCodigo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ConsultasAsignadasMedico", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ConsultasAsignadasMedicoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ConsultasAsignadasMedicoAsync(string strCodigo, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ConsultaEspecialidadFechas", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ConsultaEspecialidadFechasResponse")]
        System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ConsultaEspecialidadFechas(System.Nullable<System.DateTime> fecIni, System.Nullable<System.DateTime> fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_ConsultaEspecialidadFechas", ReplyAction="http://tempuri.org/IServicioConsultas/sp_ConsultaEspecialidadFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ConsultaEspecialidadFechasAsync(System.Nullable<System.DateTime> fecIni, System.Nullable<System.DateTime> fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_GetConsultasByDate", ReplyAction="http://tempuri.org/IServicioConsultas/sp_GetConsultasByDateResponse")]
        System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_GetConsultasByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/sp_GetConsultasByDate", ReplyAction="http://tempuri.org/IServicioConsultas/sp_GetConsultasByDateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_GetConsultasByDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioConsultasChannel : ProxyConsultas.IServicioConsultas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioConsultasClient : System.ServiceModel.ClientBase<ProxyConsultas.IServicioConsultas>, ProxyConsultas.IServicioConsultas
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioConsultasClient() : 
                base(ServicioConsultasClient.GetDefaultBinding(), ServicioConsultasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioConsultas.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConsultasClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioConsultasClient.GetBindingForEndpoint(endpointConfiguration), ServicioConsultasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConsultasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioConsultasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConsultasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioConsultasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_VerConsultasPendientes()
        {
            return base.Channel.sp_VerConsultasPendientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_VerConsultasPendientesAsync()
        {
            return base.Channel.sp_VerConsultasPendientesAsync();
        }
        
        public System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ListarConsultasPaciente(string strCodigo, string estado)
        {
            return base.Channel.sp_ListarConsultasPaciente(strCodigo, estado);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ListarConsultasPacienteAsync(string strCodigo, string estado)
        {
            return base.Channel.sp_ListarConsultasPacienteAsync(strCodigo, estado);
        }
        
        public System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ConsultasAsignadasMedico(string strCodigo, string estado)
        {
            return base.Channel.sp_ConsultasAsignadasMedico(strCodigo, estado);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ConsultasAsignadasMedicoAsync(string strCodigo, string estado)
        {
            return base.Channel.sp_ConsultasAsignadasMedicoAsync(strCodigo, estado);
        }
        
        public System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_ConsultaEspecialidadFechas(System.Nullable<System.DateTime> fecIni, System.Nullable<System.DateTime> fecFin)
        {
            return base.Channel.sp_ConsultaEspecialidadFechas(fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_ConsultaEspecialidadFechasAsync(System.Nullable<System.DateTime> fecIni, System.Nullable<System.DateTime> fecFin)
        {
            return base.Channel.sp_ConsultaEspecialidadFechasAsync(fecIni, fecFin);
        }
        
        public System.Collections.Generic.List<ProxyConsultas.ResultConsultas> sp_GetConsultasByDate(System.DateTime date)
        {
            return base.Channel.sp_GetConsultasByDate(date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyConsultas.ResultConsultas>> sp_GetConsultasByDateAsync(System.DateTime date)
        {
            return base.Channel.sp_GetConsultasByDateAsync(date);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConsultas))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConsultas))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_CheckSalud/ServicioConsultas/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioConsultasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioConsultas);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioConsultasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioConsultas);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioConsultas,
        }
    }
}
