//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyMedico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class MedicoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNomMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_MedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecNacMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecUltModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuUltModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numColegiaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMedico {
            get {
                return this.ApeMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMedicoField, value) != true)) {
                    this.ApeMedicoField = value;
                    this.RaisePropertyChanged("ApeMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomMedico {
            get {
                return this.ApeNomMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNomMedicoField, value) != true)) {
                    this.ApeNomMedicoField = value;
                    this.RaisePropertyChanged("ApeNomMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEspecialidad {
            get {
                return this.CodEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEspecialidadField, value) != true)) {
                    this.CodEspecialidadField = value;
                    this.RaisePropertyChanged("CodEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMedico {
            get {
                return this.CodMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodMedicoField, value) != true)) {
                    this.CodMedicoField = value;
                    this.RaisePropertyChanged("CodMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecMedico {
            get {
                return this.DirecMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecMedicoField, value) != true)) {
                    this.DirecMedicoField = value;
                    this.RaisePropertyChanged("DirecMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniMedico {
            get {
                return this.DniMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.DniMedicoField, value) != true)) {
                    this.DniMedicoField = value;
                    this.RaisePropertyChanged("DniMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailMedico {
            get {
                return this.EmailMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailMedicoField, value) != true)) {
                    this.EmailMedicoField = value;
                    this.RaisePropertyChanged("EmailMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Medico {
            get {
                return this.Est_MedicoField;
            }
            set {
                if ((this.Est_MedicoField.Equals(value) != true)) {
                    this.Est_MedicoField = value;
                    this.RaisePropertyChanged("Est_Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso {
            get {
                return this.FecIngresoField;
            }
            set {
                if ((this.FecIngresoField.Equals(value) != true)) {
                    this.FecIngresoField = value;
                    this.RaisePropertyChanged("FecIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNacMedico {
            get {
                return this.FecNacMedicoField;
            }
            set {
                if ((this.FecNacMedicoField.Equals(value) != true)) {
                    this.FecNacMedicoField = value;
                    this.RaisePropertyChanged("FecNacMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro {
            get {
                return this.FecRegistroField;
            }
            set {
                if ((this.FecRegistroField.Equals(value) != true)) {
                    this.FecRegistroField = value;
                    this.RaisePropertyChanged("FecRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecUltMod {
            get {
                return this.FecUltModField;
            }
            set {
                if ((this.FecUltModField.Equals(value) != true)) {
                    this.FecUltModField = value;
                    this.RaisePropertyChanged("FecUltMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginUsuario {
            get {
                return this.LoginUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginUsuarioField, value) != true)) {
                    this.LoginUsuarioField = value;
                    this.RaisePropertyChanged("LoginUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomMedico {
            get {
                return this.NomMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomMedicoField, value) != true)) {
                    this.NomMedicoField = value;
                    this.RaisePropertyChanged("NomMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuRegistro {
            get {
                return this.UsuRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuRegistroField, value) != true)) {
                    this.UsuRegistroField = value;
                    this.RaisePropertyChanged("UsuRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuUltMod {
            get {
                return this.UsuUltModField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuUltModField, value) != true)) {
                    this.UsuUltModField = value;
                    this.RaisePropertyChanged("UsuUltMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numColegiatura {
            get {
                return this.numColegiaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.numColegiaturaField, value) != true)) {
                    this.numColegiaturaField = value;
                    this.RaisePropertyChanged("numColegiatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMedico.IServicioMedico")]
    public interface IServicioMedico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ListarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ListarMedicoResponse")]
        TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC[] usp_ListarMedico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ListarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ListarMedicoResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC[]> usp_ListarMedicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_InsertarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_InsertarMedicoResponse")]
        bool usp_InsertarMedico(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_InsertarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_InsertarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarMedicoAsync(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ActualizarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ActualizarMedicoResponse")]
        bool usp_ActualizarMedico(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ActualizarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ActualizarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarMedicoAsync(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_EliminarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_EliminarMedicoResponse")]
        bool usp_EliminarMedico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_EliminarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_EliminarMedicoResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarMedicoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ConsultarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ConsultarMedicoResponse")]
        TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC usp_ConsultarMedico(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMedico/usp_ConsultarMedico", ReplyAction="http://tempuri.org/IServicioMedico/usp_ConsultarMedicoResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC> usp_ConsultarMedicoAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMedicoChannel : TestWeb_WCF_CheckSalud.ProxyMedico.IServicioMedico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMedicoClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyMedico.IServicioMedico>, TestWeb_WCF_CheckSalud.ProxyMedico.IServicioMedico {
        
        public ServicioMedicoClient() {
        }
        
        public ServicioMedicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMedicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMedicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMedicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC[] usp_ListarMedico() {
            return base.Channel.usp_ListarMedico();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC[]> usp_ListarMedicoAsync() {
            return base.Channel.usp_ListarMedicoAsync();
        }
        
        public bool usp_InsertarMedico(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC) {
            return base.Channel.usp_InsertarMedico(objMedicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarMedicoAsync(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC) {
            return base.Channel.usp_InsertarMedicoAsync(objMedicoDC);
        }
        
        public bool usp_ActualizarMedico(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC) {
            return base.Channel.usp_ActualizarMedico(objMedicoDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarMedicoAsync(TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC objMedicoDC) {
            return base.Channel.usp_ActualizarMedicoAsync(objMedicoDC);
        }
        
        public bool usp_EliminarMedico(string strCodigo) {
            return base.Channel.usp_EliminarMedico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarMedicoAsync(string strCodigo) {
            return base.Channel.usp_EliminarMedicoAsync(strCodigo);
        }
        
        public TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC usp_ConsultarMedico(string strCodigo) {
            return base.Channel.usp_ConsultarMedico(strCodigo);
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyMedico.MedicoDC> usp_ConsultarMedicoAsync(string strCodigo) {
            return base.Channel.usp_ConsultarMedicoAsync(strCodigo);
        }
    }
}
