//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyEmpresa
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    public partial class EmpresaDC : object
    {
        
        private string DirecEmpresaField;
        
        private int Est_EmpresaField;
        
        private string EstadoField;
        
        private System.DateTime FecIngresoField;
        
        private string IdUbigeoField;
        
        private string RazSocEmpresaField;
        
        private string RepEmpresaField;
        
        private string RucEmpresaField;
        
        private string TelEmpresaField;
        
        private string codEmpresaField;
        
        private string departamentoField;
        
        private string distritoField;
        
        private string provinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecEmpresa
        {
            get
            {
                return this.DirecEmpresaField;
            }
            set
            {
                this.DirecEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Empresa
        {
            get
            {
                return this.Est_EmpresaField;
            }
            set
            {
                this.Est_EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso
        {
            get
            {
                return this.FecIngresoField;
            }
            set
            {
                this.FecIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo
        {
            get
            {
                return this.IdUbigeoField;
            }
            set
            {
                this.IdUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazSocEmpresa
        {
            get
            {
                return this.RazSocEmpresaField;
            }
            set
            {
                this.RazSocEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepEmpresa
        {
            get
            {
                return this.RepEmpresaField;
            }
            set
            {
                this.RepEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucEmpresa
        {
            get
            {
                return this.RucEmpresaField;
            }
            set
            {
                this.RucEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelEmpresa
        {
            get
            {
                return this.TelEmpresaField;
            }
            set
            {
                this.TelEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEmpresa
        {
            get
            {
                return this.codEmpresaField;
            }
            set
            {
                this.codEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito
        {
            get
            {
                return this.distritoField;
            }
            set
            {
                this.distritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEmpresa.IServicioEmpresa")]
    public interface IServicioEmpresa
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresaResponse")]
        System.Collections.Generic.List<ProxyEmpresa.EmpresaDC> usp_ListarEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEmpresa.EmpresaDC>> usp_ListarEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresaResponse")]
        bool usp_InsertarEmpresa(ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarEmpresaAsync(ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresaResponse")]
        bool usp_ActualizarEmpresa(ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarEmpresaAsync(ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresaResponse")]
        bool usp_EliminarEmpresa(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarEmpresaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresaResponse")]
        ProxyEmpresa.EmpresaDC usp_ConsultarEmpresa(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresaResponse")]
        System.Threading.Tasks.Task<ProxyEmpresa.EmpresaDC> usp_ConsultarEmpresaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ExisteRuc", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ExisteRucResponse")]
        bool usp_ExisteRuc(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ExisteRuc", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ExisteRucResponse")]
        System.Threading.Tasks.Task<bool> usp_ExisteRucAsync(string ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioEmpresaChannel : ProxyEmpresa.IServicioEmpresa, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioEmpresaClient : System.ServiceModel.ClientBase<ProxyEmpresa.IServicioEmpresa>, ProxyEmpresa.IServicioEmpresa
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEmpresaClient() : 
                base(ServicioEmpresaClient.GetDefaultBinding(), ServicioEmpresaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEmpresa.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpresaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEmpresaClient.GetBindingForEndpoint(endpointConfiguration), ServicioEmpresaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpresaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEmpresaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpresaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEmpresaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyEmpresa.EmpresaDC> usp_ListarEmpresa()
        {
            return base.Channel.usp_ListarEmpresa();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEmpresa.EmpresaDC>> usp_ListarEmpresaAsync()
        {
            return base.Channel.usp_ListarEmpresaAsync();
        }
        
        public bool usp_InsertarEmpresa(ProxyEmpresa.EmpresaDC objEmpresaDC)
        {
            return base.Channel.usp_InsertarEmpresa(objEmpresaDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarEmpresaAsync(ProxyEmpresa.EmpresaDC objEmpresaDC)
        {
            return base.Channel.usp_InsertarEmpresaAsync(objEmpresaDC);
        }
        
        public bool usp_ActualizarEmpresa(ProxyEmpresa.EmpresaDC objEmpresaDC)
        {
            return base.Channel.usp_ActualizarEmpresa(objEmpresaDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarEmpresaAsync(ProxyEmpresa.EmpresaDC objEmpresaDC)
        {
            return base.Channel.usp_ActualizarEmpresaAsync(objEmpresaDC);
        }
        
        public bool usp_EliminarEmpresa(string strCodigo)
        {
            return base.Channel.usp_EliminarEmpresa(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarEmpresaAsync(string strCodigo)
        {
            return base.Channel.usp_EliminarEmpresaAsync(strCodigo);
        }
        
        public ProxyEmpresa.EmpresaDC usp_ConsultarEmpresa(string strCodigo)
        {
            return base.Channel.usp_ConsultarEmpresa(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyEmpresa.EmpresaDC> usp_ConsultarEmpresaAsync(string strCodigo)
        {
            return base.Channel.usp_ConsultarEmpresaAsync(strCodigo);
        }
        
        public bool usp_ExisteRuc(string ruc)
        {
            return base.Channel.usp_ExisteRuc(ruc);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ExisteRucAsync(string ruc)
        {
            return base.Channel.usp_ExisteRucAsync(ruc);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEmpresa))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEmpresa))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_CheckSalud/ServicioEmpresa/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEmpresaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEmpresa);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEmpresaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEmpresa);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEmpresa,
        }
    }
}
