//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyPaciente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    public partial class PacienteDC : object
    {
        
        private string ApeNomPacienteField;
        
        private string ApePacienteField;
        
        private string CodEmpresaField;
        
        private string CodPacienteField;
        
        private string DirecPacienteField;
        
        private string DniPacienteField;
        
        private int EdadField;
        
        private string EmailPacienteField;
        
        private int Est_PacienteField;
        
        private string EstadoField;
        
        private System.DateTime FecIngresoField;
        
        private System.DateTime FecNacPacienteField;
        
        private System.DateTime FecRegistroField;
        
        private System.DateTime FecUltModField;
        
        private string IdUbigeoField;
        
        private string LugarTrabajoField;
        
        private string NomPacienteField;
        
        private string SexoField;
        
        private int Sexo_PacienteField;
        
        private string TelPacienteField;
        
        private string TipoField;
        
        private string TipoSangreField;
        
        private int Tipo_ClienteField;
        
        private int Tipo_SangreField;
        
        private string UsuRegistroField;
        
        private string UsuUltModField;
        
        private string departamentoField;
        
        private string distritoField;
        
        private string provinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomPaciente
        {
            get
            {
                return this.ApeNomPacienteField;
            }
            set
            {
                this.ApeNomPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaciente
        {
            get
            {
                return this.ApePacienteField;
            }
            set
            {
                this.ApePacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmpresa
        {
            get
            {
                return this.CodEmpresaField;
            }
            set
            {
                this.CodEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPaciente
        {
            get
            {
                return this.CodPacienteField;
            }
            set
            {
                this.CodPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecPaciente
        {
            get
            {
                return this.DirecPacienteField;
            }
            set
            {
                this.DirecPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniPaciente
        {
            get
            {
                return this.DniPacienteField;
            }
            set
            {
                this.DniPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPaciente
        {
            get
            {
                return this.EmailPacienteField;
            }
            set
            {
                this.EmailPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Paciente
        {
            get
            {
                return this.Est_PacienteField;
            }
            set
            {
                this.Est_PacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso
        {
            get
            {
                return this.FecIngresoField;
            }
            set
            {
                this.FecIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNacPaciente
        {
            get
            {
                return this.FecNacPacienteField;
            }
            set
            {
                this.FecNacPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro
        {
            get
            {
                return this.FecRegistroField;
            }
            set
            {
                this.FecRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecUltMod
        {
            get
            {
                return this.FecUltModField;
            }
            set
            {
                this.FecUltModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo
        {
            get
            {
                return this.IdUbigeoField;
            }
            set
            {
                this.IdUbigeoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarTrabajo
        {
            get
            {
                return this.LugarTrabajoField;
            }
            set
            {
                this.LugarTrabajoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPaciente
        {
            get
            {
                return this.NomPacienteField;
            }
            set
            {
                this.NomPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sexo_Paciente
        {
            get
            {
                return this.Sexo_PacienteField;
            }
            set
            {
                this.Sexo_PacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelPaciente
        {
            get
            {
                return this.TelPacienteField;
            }
            set
            {
                this.TelPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSangre
        {
            get
            {
                return this.TipoSangreField;
            }
            set
            {
                this.TipoSangreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo_Cliente
        {
            get
            {
                return this.Tipo_ClienteField;
            }
            set
            {
                this.Tipo_ClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo_Sangre
        {
            get
            {
                return this.Tipo_SangreField;
            }
            set
            {
                this.Tipo_SangreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuRegistro
        {
            get
            {
                return this.UsuRegistroField;
            }
            set
            {
                this.UsuRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuUltMod
        {
            get
            {
                return this.UsuUltModField;
            }
            set
            {
                this.UsuUltModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito
        {
            get
            {
                return this.distritoField;
            }
            set
            {
                this.distritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPaciente.IServicioPaciente")]
    public interface IServicioPaciente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ListarPacienteResponse")]
        System.Collections.Generic.List<ProxyPaciente.PacienteDC> usp_ListarPaciente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ListarPacienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyPaciente.PacienteDC>> usp_ListarPacienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_InsertarPacienteResponse")]
        bool usp_InsertarPaciente(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_InsertarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ActualizarPacienteResponse")]
        bool usp_ActualizarPaciente(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ActualizarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_EliminarPacienteResponse")]
        bool usp_EliminarPaciente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_EliminarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarPacienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ConsultarPacienteResponse")]
        ProxyPaciente.PacienteDC usp_ConsultarPaciente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ConsultarPacienteResponse")]
        System.Threading.Tasks.Task<ProxyPaciente.PacienteDC> usp_ConsultarPacienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioPacienteChannel : ProxyPaciente.IServicioPaciente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioPacienteClient : System.ServiceModel.ClientBase<ProxyPaciente.IServicioPaciente>, ProxyPaciente.IServicioPaciente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioPacienteClient() : 
                base(ServicioPacienteClient.GetDefaultBinding(), ServicioPacienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioPaciente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioPacienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioPacienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyPaciente.PacienteDC> usp_ListarPaciente()
        {
            return base.Channel.usp_ListarPaciente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyPaciente.PacienteDC>> usp_ListarPacienteAsync()
        {
            return base.Channel.usp_ListarPacienteAsync();
        }
        
        public bool usp_InsertarPaciente(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.usp_InsertarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.usp_InsertarPacienteAsync(objPacienteDC);
        }
        
        public bool usp_ActualizarPaciente(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.usp_ActualizarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarPacienteAsync(ProxyPaciente.PacienteDC objPacienteDC)
        {
            return base.Channel.usp_ActualizarPacienteAsync(objPacienteDC);
        }
        
        public bool usp_EliminarPaciente(string strCodigo)
        {
            return base.Channel.usp_EliminarPaciente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarPacienteAsync(string strCodigo)
        {
            return base.Channel.usp_EliminarPacienteAsync(strCodigo);
        }
        
        public ProxyPaciente.PacienteDC usp_ConsultarPaciente(string strCodigo)
        {
            return base.Channel.usp_ConsultarPaciente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyPaciente.PacienteDC> usp_ConsultarPacienteAsync(string strCodigo)
        {
            return base.Channel.usp_ConsultarPacienteAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioPaciente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_CheckSalud/ServicioPaciente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioPacienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioPacienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioPaciente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioPaciente,
        }
    }
}
