//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CheckSalu.AnalisisServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalisisDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class AnalisisDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAnalisis {
            get {
                return this.codAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.codAnalisisField, value) != true)) {
                    this.codAnalisisField = value;
                    this.RaisePropertyChanged("codAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descAnalisis {
            get {
                return this.descAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.descAnalisisField, value) != true)) {
                    this.descAnalisisField = value;
                    this.RaisePropertyChanged("descAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estAnalisis {
            get {
                return this.estAnalisisField;
            }
            set {
                if ((this.estAnalisisField.Equals(value) != true)) {
                    this.estAnalisisField = value;
                    this.RaisePropertyChanged("estAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnalisisServiceReference1.IServicioAnalisis")]
    public interface IServicioAnalisis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarAnalisisResponse")]
        MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC ConsultarAnalisis(string codAnalisis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarAnalisisResponse")]
        System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC> ConsultarAnalisisAsync(string codAnalisis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ListarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ListarAnalisisResponse")]
        MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC[] ListarAnalisis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ListarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ListarAnalisisResponse")]
        System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC[]> ListarAnalisisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/InsertarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/InsertarAnalisisResponse")]
        bool InsertarAnalisis(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/InsertarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/InsertarAnalisisResponse")]
        System.Threading.Tasks.Task<bool> InsertarAnalisisAsync(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ActualizarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ActualizarAnalisisResponse")]
        bool ActualizarAnalisis(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ActualizarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ActualizarAnalisisResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAnalisisAsync(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/EliminarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/EliminarAnalisisResponse")]
        bool EliminarAnalisis(string codAnalisis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/EliminarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/EliminarAnalisisResponse")]
        System.Threading.Tasks.Task<bool> EliminarAnalisisAsync(string codAnalisis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarUltimoAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarUltimoAnalisisResponse")]
        MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC ConsultarUltimoAnalisis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarUltimoAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarUltimoAnalisisResponse")]
        System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC> ConsultarUltimoAnalisisAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAnalisisChannel : MVC_CheckSalu.AnalisisServiceReference1.IServicioAnalisis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAnalisisClient : System.ServiceModel.ClientBase<MVC_CheckSalu.AnalisisServiceReference1.IServicioAnalisis>, MVC_CheckSalu.AnalisisServiceReference1.IServicioAnalisis {
        
        public ServicioAnalisisClient() {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnalisisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC ConsultarAnalisis(string codAnalisis) {
            return base.Channel.ConsultarAnalisis(codAnalisis);
        }
        
        public System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC> ConsultarAnalisisAsync(string codAnalisis) {
            return base.Channel.ConsultarAnalisisAsync(codAnalisis);
        }
        
        public MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC[] ListarAnalisis() {
            return base.Channel.ListarAnalisis();
        }
        
        public System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC[]> ListarAnalisisAsync() {
            return base.Channel.ListarAnalisisAsync();
        }
        
        public bool InsertarAnalisis(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC) {
            return base.Channel.InsertarAnalisis(objAnalisisDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAnalisisAsync(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC) {
            return base.Channel.InsertarAnalisisAsync(objAnalisisDC);
        }
        
        public bool ActualizarAnalisis(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC) {
            return base.Channel.ActualizarAnalisis(objAnalisisDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAnalisisAsync(MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC objAnalisisDC) {
            return base.Channel.ActualizarAnalisisAsync(objAnalisisDC);
        }
        
        public bool EliminarAnalisis(string codAnalisis) {
            return base.Channel.EliminarAnalisis(codAnalisis);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAnalisisAsync(string codAnalisis) {
            return base.Channel.EliminarAnalisisAsync(codAnalisis);
        }
        
        public MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC ConsultarUltimoAnalisis() {
            return base.Channel.ConsultarUltimoAnalisis();
        }
        
        public System.Threading.Tasks.Task<MVC_CheckSalu.AnalisisServiceReference1.AnalisisDC> ConsultarUltimoAnalisisAsync() {
            return base.Channel.ConsultarUltimoAnalisisAsync();
        }
    }
}
