//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyPaciente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class PacienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNomPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecNacPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecUltModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Sexo_PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoSangreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tipo_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tipo_SangreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuUltModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomPaciente {
            get {
                return this.ApeNomPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNomPacienteField, value) != true)) {
                    this.ApeNomPacienteField = value;
                    this.RaisePropertyChanged("ApeNomPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaciente {
            get {
                return this.ApePacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePacienteField, value) != true)) {
                    this.ApePacienteField = value;
                    this.RaisePropertyChanged("ApePaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEmpresa {
            get {
                return this.CodEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEmpresaField, value) != true)) {
                    this.CodEmpresaField = value;
                    this.RaisePropertyChanged("CodEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPaciente {
            get {
                return this.CodPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodPacienteField, value) != true)) {
                    this.CodPacienteField = value;
                    this.RaisePropertyChanged("CodPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecPaciente {
            get {
                return this.DirecPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecPacienteField, value) != true)) {
                    this.DirecPacienteField = value;
                    this.RaisePropertyChanged("DirecPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DniPaciente {
            get {
                return this.DniPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.DniPacienteField, value) != true)) {
                    this.DniPacienteField = value;
                    this.RaisePropertyChanged("DniPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPaciente {
            get {
                return this.EmailPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPacienteField, value) != true)) {
                    this.EmailPacienteField = value;
                    this.RaisePropertyChanged("EmailPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Paciente {
            get {
                return this.Est_PacienteField;
            }
            set {
                if ((this.Est_PacienteField.Equals(value) != true)) {
                    this.Est_PacienteField = value;
                    this.RaisePropertyChanged("Est_Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso {
            get {
                return this.FecIngresoField;
            }
            set {
                if ((this.FecIngresoField.Equals(value) != true)) {
                    this.FecIngresoField = value;
                    this.RaisePropertyChanged("FecIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNacPaciente {
            get {
                return this.FecNacPacienteField;
            }
            set {
                if ((this.FecNacPacienteField.Equals(value) != true)) {
                    this.FecNacPacienteField = value;
                    this.RaisePropertyChanged("FecNacPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecRegistro {
            get {
                return this.FecRegistroField;
            }
            set {
                if ((this.FecRegistroField.Equals(value) != true)) {
                    this.FecRegistroField = value;
                    this.RaisePropertyChanged("FecRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecUltMod {
            get {
                return this.FecUltModField;
            }
            set {
                if ((this.FecUltModField.Equals(value) != true)) {
                    this.FecUltModField = value;
                    this.RaisePropertyChanged("FecUltMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarTrabajo {
            get {
                return this.LugarTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarTrabajoField, value) != true)) {
                    this.LugarTrabajoField = value;
                    this.RaisePropertyChanged("LugarTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPaciente {
            get {
                return this.NomPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPacienteField, value) != true)) {
                    this.NomPacienteField = value;
                    this.RaisePropertyChanged("NomPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sexo_Paciente {
            get {
                return this.Sexo_PacienteField;
            }
            set {
                if ((this.Sexo_PacienteField.Equals(value) != true)) {
                    this.Sexo_PacienteField = value;
                    this.RaisePropertyChanged("Sexo_Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelPaciente {
            get {
                return this.TelPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.TelPacienteField, value) != true)) {
                    this.TelPacienteField = value;
                    this.RaisePropertyChanged("TelPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSangre {
            get {
                return this.TipoSangreField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoSangreField, value) != true)) {
                    this.TipoSangreField = value;
                    this.RaisePropertyChanged("TipoSangre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo_Cliente {
            get {
                return this.Tipo_ClienteField;
            }
            set {
                if ((this.Tipo_ClienteField.Equals(value) != true)) {
                    this.Tipo_ClienteField = value;
                    this.RaisePropertyChanged("Tipo_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo_Sangre {
            get {
                return this.Tipo_SangreField;
            }
            set {
                if ((this.Tipo_SangreField.Equals(value) != true)) {
                    this.Tipo_SangreField = value;
                    this.RaisePropertyChanged("Tipo_Sangre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuRegistro {
            get {
                return this.UsuRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuRegistroField, value) != true)) {
                    this.UsuRegistroField = value;
                    this.RaisePropertyChanged("UsuRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuUltMod {
            get {
                return this.UsuUltModField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuUltModField, value) != true)) {
                    this.UsuUltModField = value;
                    this.RaisePropertyChanged("UsuUltMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPaciente.IServicioPaciente")]
    public interface IServicioPaciente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ListarPacienteResponse")]
        TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC[] usp_ListarPaciente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ListarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ListarPacienteResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC[]> usp_ListarPacienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_InsertarPacienteResponse")]
        bool usp_InsertarPaciente(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_InsertarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_InsertarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarPacienteAsync(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ActualizarPacienteResponse")]
        bool usp_ActualizarPaciente(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ActualizarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ActualizarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarPacienteAsync(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_EliminarPacienteResponse")]
        bool usp_EliminarPaciente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_EliminarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_EliminarPacienteResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarPacienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ConsultarPacienteResponse")]
        TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC usp_ConsultarPaciente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPaciente/usp_ConsultarPaciente", ReplyAction="http://tempuri.org/IServicioPaciente/usp_ConsultarPacienteResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC> usp_ConsultarPacienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPacienteChannel : TestWeb_WCF_CheckSalud.ProxyPaciente.IServicioPaciente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPacienteClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyPaciente.IServicioPaciente>, TestWeb_WCF_CheckSalud.ProxyPaciente.IServicioPaciente {
        
        public ServicioPacienteClient() {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPacienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPacienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC[] usp_ListarPaciente() {
            return base.Channel.usp_ListarPaciente();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC[]> usp_ListarPacienteAsync() {
            return base.Channel.usp_ListarPacienteAsync();
        }
        
        public bool usp_InsertarPaciente(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC) {
            return base.Channel.usp_InsertarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarPacienteAsync(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC) {
            return base.Channel.usp_InsertarPacienteAsync(objPacienteDC);
        }
        
        public bool usp_ActualizarPaciente(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC) {
            return base.Channel.usp_ActualizarPaciente(objPacienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarPacienteAsync(TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC objPacienteDC) {
            return base.Channel.usp_ActualizarPacienteAsync(objPacienteDC);
        }
        
        public bool usp_EliminarPaciente(string strCodigo) {
            return base.Channel.usp_EliminarPaciente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarPacienteAsync(string strCodigo) {
            return base.Channel.usp_EliminarPacienteAsync(strCodigo);
        }
        
        public TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC usp_ConsultarPaciente(string strCodigo) {
            return base.Channel.usp_ConsultarPaciente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyPaciente.PacienteDC> usp_ConsultarPacienteAsync(string strCodigo) {
            return base.Channel.usp_ConsultarPacienteAsync(strCodigo);
        }
    }
}
