//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyUbicacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class UbicacionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbicacion.IServicioUbicacion")]
    public interface IServicioUbicacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbicacion/usp_ListarUbicacion", ReplyAction="http://tempuri.org/IServicioUbicacion/usp_ListarUbicacionResponse")]
        TestWeb_WCF_CheckSalud.ProxyUbicacion.UbicacionDC[] usp_ListarUbicacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbicacion/usp_ListarUbicacion", ReplyAction="http://tempuri.org/IServicioUbicacion/usp_ListarUbicacionResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyUbicacion.UbicacionDC[]> usp_ListarUbicacionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbicacionChannel : TestWeb_WCF_CheckSalud.ProxyUbicacion.IServicioUbicacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbicacionClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyUbicacion.IServicioUbicacion>, TestWeb_WCF_CheckSalud.ProxyUbicacion.IServicioUbicacion {
        
        public ServicioUbicacionClient() {
        }
        
        public ServicioUbicacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbicacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbicacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbicacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyUbicacion.UbicacionDC[] usp_ListarUbicacion() {
            return base.Channel.usp_ListarUbicacion();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyUbicacion.UbicacionDC[]> usp_ListarUbicacionAsync() {
            return base.Channel.usp_ListarUbicacionAsync();
        }
    }
}
