//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDCheckSaludEntities : DbContext
    {
        public BDCheckSaludEntities()
            : base("name=BDCheckSaludEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Analisis> Tb_Analisis { get; set; }
        public virtual DbSet<Tb_Auditor> Tb_Auditor { get; set; }
        public virtual DbSet<Tb_Consultas> Tb_Consultas { get; set; }
        public virtual DbSet<Tb_Empresa> Tb_Empresa { get; set; }
        public virtual DbSet<Tb_Enfermedad> Tb_Enfermedad { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Evaluacion> Tb_Evaluacion { get; set; }
        public virtual DbSet<Tb_Horario> Tb_Horario { get; set; }
        public virtual DbSet<Tb_Medico> Tb_Medico { get; set; }
        public virtual DbSet<Tb_Paciente> Tb_Paciente { get; set; }
        public virtual DbSet<Tb_Resultados> Tb_Resultados { get; set; }
        public virtual DbSet<Tb_Ubicacion> Tb_Ubicacion { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int sp_ActualizarConsultasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarConsultasPendientes");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_CancelarConsulta(string codConsulta)
        {
            var codConsultaParameter = codConsulta != null ?
                new ObjectParameter("codConsulta", codConsulta) :
                new ObjectParameter("codConsulta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CancelarConsulta", codConsultaParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaEspecialidadFechas_Result> sp_ConsultaEspecialidadFechas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaEspecialidadFechas_Result>("sp_ConsultaEspecialidadFechas", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<sp_ConsultaMedicosEspecialidad_Result> sp_ConsultaMedicosEspecialidad(string codEspecialidad)
        {
            var codEspecialidadParameter = codEspecialidad != null ?
                new ObjectParameter("codEspecialidad", codEspecialidad) :
                new ObjectParameter("codEspecialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultaMedicosEspecialidad_Result>("sp_ConsultaMedicosEspecialidad", codEspecialidadParameter);
        }
    
        public virtual ObjectResult<sp_ConsultasAsignadasMedico_Result> sp_ConsultasAsignadasMedico(string codMedico, string estado)
        {
            var codMedicoParameter = codMedico != null ?
                new ObjectParameter("codMedico", codMedico) :
                new ObjectParameter("codMedico", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultasAsignadasMedico_Result>("sp_ConsultasAsignadasMedico", codMedicoParameter, estadoParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_GetConsultasByDate_Result> sp_GetConsultasByDate(Nullable<System.DateTime> fechaConsulta)
        {
            var fechaConsultaParameter = fechaConsulta.HasValue ?
                new ObjectParameter("FechaConsulta", fechaConsulta) :
                new ObjectParameter("FechaConsulta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetConsultasByDate_Result>("sp_GetConsultasByDate", fechaConsultaParameter);
        }
    
        public virtual ObjectResult<sp_GetConsultasByDate1_Result> sp_GetConsultasByDate1(Nullable<System.DateTime> fechaConsulta)
        {
            var fechaConsultaParameter = fechaConsulta.HasValue ?
                new ObjectParameter("FechaConsulta", fechaConsulta) :
                new ObjectParameter("FechaConsulta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetConsultasByDate1_Result>("sp_GetConsultasByDate1", fechaConsultaParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_ListarConsultasPaciente_Result> sp_ListarConsultasPaciente(string dniPaciente, string estado)
        {
            var dniPacienteParameter = dniPaciente != null ?
                new ObjectParameter("dniPaciente", dniPaciente) :
                new ObjectParameter("dniPaciente", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarConsultasPaciente_Result>("sp_ListarConsultasPaciente", dniPacienteParameter, estadoParameter);
        }
    
        public virtual ObjectResult<sp_ListarEspecialidad_Result> sp_ListarEspecialidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEspecialidad_Result>("sp_ListarEspecialidad");
        }
    
        public virtual ObjectResult<sp_ListarMedicosEspecialidad_Result> sp_ListarMedicosEspecialidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarMedicosEspecialidad_Result>("sp_ListarMedicosEspecialidad");
        }
    
        public virtual int sp_ProgramarConsulta(string codPaciente, string codMedico, string motivoConsulta, Nullable<System.DateTime> fechaConsulta)
        {
            var codPacienteParameter = codPaciente != null ?
                new ObjectParameter("codPaciente", codPaciente) :
                new ObjectParameter("codPaciente", typeof(string));
    
            var codMedicoParameter = codMedico != null ?
                new ObjectParameter("codMedico", codMedico) :
                new ObjectParameter("codMedico", typeof(string));
    
            var motivoConsultaParameter = motivoConsulta != null ?
                new ObjectParameter("motivoConsulta", motivoConsulta) :
                new ObjectParameter("motivoConsulta", typeof(string));
    
            var fechaConsultaParameter = fechaConsulta.HasValue ?
                new ObjectParameter("fechaConsulta", fechaConsulta) :
                new ObjectParameter("fechaConsulta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProgramarConsulta", codPacienteParameter, codMedicoParameter, motivoConsultaParameter, fechaConsultaParameter);
        }
    
        public virtual int sp_RegistrarResultadosConsulta(string codConsulta, string resultados)
        {
            var codConsultaParameter = codConsulta != null ?
                new ObjectParameter("codConsulta", codConsulta) :
                new ObjectParameter("codConsulta", typeof(string));
    
            var resultadosParameter = resultados != null ?
                new ObjectParameter("resultados", resultados) :
                new ObjectParameter("resultados", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarResultadosConsulta", codConsultaParameter, resultadosParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_ResultadosAnalisisPaciente_Result> sp_ResultadosAnalisisPaciente(string codPaciente)
        {
            var codPacienteParameter = codPaciente != null ?
                new ObjectParameter("codPaciente", codPaciente) :
                new ObjectParameter("codPaciente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ResultadosAnalisisPaciente_Result>("sp_ResultadosAnalisisPaciente", codPacienteParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_VerConsultasPendientes_Result> sp_VerConsultasPendientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_VerConsultasPendientes_Result>("sp_VerConsultasPendientes");
        }
    
        public virtual int usp_ActualizarAnalisis(string vCod, string vDes, Nullable<decimal> vCos, Nullable<int> vEst, string vUsu_Ult_Mod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vDesParameter = vDes != null ?
                new ObjectParameter("vDes", vDes) :
                new ObjectParameter("vDes", typeof(string));
    
            var vCosParameter = vCos.HasValue ?
                new ObjectParameter("vCos", vCos) :
                new ObjectParameter("vCos", typeof(decimal));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(int));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAnalisis", vCodParameter, vDesParameter, vCosParameter, vEstParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_ActualizarEmpresa(string vcodEmpresa, string vRaz_soc_emp, string vDir_emp, string vTel_emp, string vRuc_emp, string vRep_emp, string vId_ubigeo, Nullable<int> vestado)
        {
            var vcodEmpresaParameter = vcodEmpresa != null ?
                new ObjectParameter("VcodEmpresa", vcodEmpresa) :
                new ObjectParameter("VcodEmpresa", typeof(string));
    
            var vRaz_soc_empParameter = vRaz_soc_emp != null ?
                new ObjectParameter("VRaz_soc_emp", vRaz_soc_emp) :
                new ObjectParameter("VRaz_soc_emp", typeof(string));
    
            var vDir_empParameter = vDir_emp != null ?
                new ObjectParameter("VDir_emp", vDir_emp) :
                new ObjectParameter("VDir_emp", typeof(string));
    
            var vTel_empParameter = vTel_emp != null ?
                new ObjectParameter("VTel_emp", vTel_emp) :
                new ObjectParameter("VTel_emp", typeof(string));
    
            var vRuc_empParameter = vRuc_emp != null ?
                new ObjectParameter("VRuc_emp", vRuc_emp) :
                new ObjectParameter("VRuc_emp", typeof(string));
    
            var vRep_empParameter = vRep_emp != null ?
                new ObjectParameter("VRep_emp", vRep_emp) :
                new ObjectParameter("VRep_emp", typeof(string));
    
            var vId_ubigeoParameter = vId_ubigeo != null ?
                new ObjectParameter("VId_ubigeo", vId_ubigeo) :
                new ObjectParameter("VId_ubigeo", typeof(string));
    
            var vestadoParameter = vestado.HasValue ?
                new ObjectParameter("Vestado", vestado) :
                new ObjectParameter("Vestado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEmpresa", vcodEmpresaParameter, vRaz_soc_empParameter, vDir_empParameter, vTel_empParameter, vRuc_empParameter, vRep_empParameter, vId_ubigeoParameter, vestadoParameter);
        }
    
        public virtual int usp_ActualizarEstadoPaciente(string vCod, string vNom, string vApe, Nullable<System.DateTime> vFNac, string vDni, Nullable<int> vSexo, string vDir, string vSang, string vEmail, Nullable<System.DateTime> vFIngr, string vTelef, Nullable<int> vEsta, Nullable<int> vTipo, string vCEmpr, string vUsu_Ult_Mod, string vId_Ubigeo)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vNomParameter = vNom != null ?
                new ObjectParameter("vNom", vNom) :
                new ObjectParameter("vNom", typeof(string));
    
            var vApeParameter = vApe != null ?
                new ObjectParameter("vApe", vApe) :
                new ObjectParameter("vApe", typeof(string));
    
            var vFNacParameter = vFNac.HasValue ?
                new ObjectParameter("vFNac", vFNac) :
                new ObjectParameter("vFNac", typeof(System.DateTime));
    
            var vDniParameter = vDni != null ?
                new ObjectParameter("vDni", vDni) :
                new ObjectParameter("vDni", typeof(string));
    
            var vSexoParameter = vSexo.HasValue ?
                new ObjectParameter("vSexo", vSexo) :
                new ObjectParameter("vSexo", typeof(int));
    
            var vDirParameter = vDir != null ?
                new ObjectParameter("vDir", vDir) :
                new ObjectParameter("vDir", typeof(string));
    
            var vSangParameter = vSang != null ?
                new ObjectParameter("vSang", vSang) :
                new ObjectParameter("vSang", typeof(string));
    
            var vEmailParameter = vEmail != null ?
                new ObjectParameter("vEmail", vEmail) :
                new ObjectParameter("vEmail", typeof(string));
    
            var vFIngrParameter = vFIngr.HasValue ?
                new ObjectParameter("vFIngr", vFIngr) :
                new ObjectParameter("vFIngr", typeof(System.DateTime));
    
            var vTelefParameter = vTelef != null ?
                new ObjectParameter("vTelef", vTelef) :
                new ObjectParameter("vTelef", typeof(string));
    
            var vEstaParameter = vEsta.HasValue ?
                new ObjectParameter("vEsta", vEsta) :
                new ObjectParameter("vEsta", typeof(int));
    
            var vTipoParameter = vTipo.HasValue ?
                new ObjectParameter("vTipo", vTipo) :
                new ObjectParameter("vTipo", typeof(int));
    
            var vCEmprParameter = vCEmpr != null ?
                new ObjectParameter("vCEmpr", vCEmpr) :
                new ObjectParameter("vCEmpr", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEstadoPaciente", vCodParameter, vNomParameter, vApeParameter, vFNacParameter, vDniParameter, vSexoParameter, vDirParameter, vSangParameter, vEmailParameter, vFIngrParameter, vTelefParameter, vEstaParameter, vTipoParameter, vCEmprParameter, vUsu_Ult_ModParameter, vId_UbigeoParameter);
        }
    
        public virtual int usp_ActualizarMedico(string vCodMedico, string dniMedic, string nomMedico, string apeMedico, string numColegiatura, Nullable<System.DateTime> fechaNacimiento, string emailMedico, string direcMedico, Nullable<int> estado, string codEspecialidad, string login_Usuario, string usu_Ult_Mod, string id_Ubigeo)
        {
            var vCodMedicoParameter = vCodMedico != null ?
                new ObjectParameter("vCodMedico", vCodMedico) :
                new ObjectParameter("vCodMedico", typeof(string));
    
            var dniMedicParameter = dniMedic != null ?
                new ObjectParameter("dniMedic", dniMedic) :
                new ObjectParameter("dniMedic", typeof(string));
    
            var nomMedicoParameter = nomMedico != null ?
                new ObjectParameter("nomMedico", nomMedico) :
                new ObjectParameter("nomMedico", typeof(string));
    
            var apeMedicoParameter = apeMedico != null ?
                new ObjectParameter("apeMedico", apeMedico) :
                new ObjectParameter("apeMedico", typeof(string));
    
            var numColegiaturaParameter = numColegiatura != null ?
                new ObjectParameter("numColegiatura", numColegiatura) :
                new ObjectParameter("numColegiatura", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("fechaNacimiento", fechaNacimiento) :
                new ObjectParameter("fechaNacimiento", typeof(System.DateTime));
    
            var emailMedicoParameter = emailMedico != null ?
                new ObjectParameter("emailMedico", emailMedico) :
                new ObjectParameter("emailMedico", typeof(string));
    
            var direcMedicoParameter = direcMedico != null ?
                new ObjectParameter("direcMedico", direcMedico) :
                new ObjectParameter("direcMedico", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var codEspecialidadParameter = codEspecialidad != null ?
                new ObjectParameter("codEspecialidad", codEspecialidad) :
                new ObjectParameter("codEspecialidad", typeof(string));
    
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMedico", vCodMedicoParameter, dniMedicParameter, nomMedicoParameter, apeMedicoParameter, numColegiaturaParameter, fechaNacimientoParameter, emailMedicoParameter, direcMedicoParameter, estadoParameter, codEspecialidadParameter, login_UsuarioParameter, usu_Ult_ModParameter, id_UbigeoParameter);
        }
    
        public virtual int usp_ActualizarResultado(string vCod, Nullable<decimal> vPeso, Nullable<decimal> vAltura, string vSangre, string vOrina, string vEkg, string vSpiro, string vPsico, string vXray, string vAudi, string vVisi, string vCodEnfe, string vRecom, string vCodPac, string vUsu_Ult_Mod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vPesoParameter = vPeso.HasValue ?
                new ObjectParameter("vPeso", vPeso) :
                new ObjectParameter("vPeso", typeof(decimal));
    
            var vAlturaParameter = vAltura.HasValue ?
                new ObjectParameter("vAltura", vAltura) :
                new ObjectParameter("vAltura", typeof(decimal));
    
            var vSangreParameter = vSangre != null ?
                new ObjectParameter("vSangre", vSangre) :
                new ObjectParameter("vSangre", typeof(string));
    
            var vOrinaParameter = vOrina != null ?
                new ObjectParameter("vOrina", vOrina) :
                new ObjectParameter("vOrina", typeof(string));
    
            var vEkgParameter = vEkg != null ?
                new ObjectParameter("vEkg", vEkg) :
                new ObjectParameter("vEkg", typeof(string));
    
            var vSpiroParameter = vSpiro != null ?
                new ObjectParameter("vSpiro", vSpiro) :
                new ObjectParameter("vSpiro", typeof(string));
    
            var vPsicoParameter = vPsico != null ?
                new ObjectParameter("vPsico", vPsico) :
                new ObjectParameter("vPsico", typeof(string));
    
            var vXrayParameter = vXray != null ?
                new ObjectParameter("vXray", vXray) :
                new ObjectParameter("vXray", typeof(string));
    
            var vAudiParameter = vAudi != null ?
                new ObjectParameter("vAudi", vAudi) :
                new ObjectParameter("vAudi", typeof(string));
    
            var vVisiParameter = vVisi != null ?
                new ObjectParameter("vVisi", vVisi) :
                new ObjectParameter("vVisi", typeof(string));
    
            var vCodEnfeParameter = vCodEnfe != null ?
                new ObjectParameter("vCodEnfe", vCodEnfe) :
                new ObjectParameter("vCodEnfe", typeof(string));
    
            var vRecomParameter = vRecom != null ?
                new ObjectParameter("vRecom", vRecom) :
                new ObjectParameter("vRecom", typeof(string));
    
            var vCodPacParameter = vCodPac != null ?
                new ObjectParameter("vCodPac", vCodPac) :
                new ObjectParameter("vCodPac", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarResultado", vCodParameter, vPesoParameter, vAlturaParameter, vSangreParameter, vOrinaParameter, vEkgParameter, vSpiroParameter, vPsicoParameter, vXrayParameter, vAudiParameter, vVisiParameter, vCodEnfeParameter, vRecomParameter, vCodPacParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarAnalisis_Result> usp_ConsultarAnalisis(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarAnalisis_Result>("usp_ConsultarAnalisis", vCodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpresa_Result> usp_ConsultarEmpresa(string vcodEmpresa)
        {
            var vcodEmpresaParameter = vcodEmpresa != null ?
                new ObjectParameter("VcodEmpresa", vcodEmpresa) :
                new ObjectParameter("VcodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpresa_Result>("usp_ConsultarEmpresa", vcodEmpresaParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarMedico_Result> usp_ConsultarMedico(string vCodMedico)
        {
            var vCodMedicoParameter = vCodMedico != null ?
                new ObjectParameter("vCodMedico", vCodMedico) :
                new ObjectParameter("vCodMedico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarMedico_Result>("usp_ConsultarMedico", vCodMedicoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarPaciente_Result> usp_ConsultarPaciente(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarPaciente_Result>("usp_ConsultarPaciente", vCodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarResultado_Result> usp_ConsultarResultado(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarResultado_Result>("usp_ConsultarResultado", vCodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usuario)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuarioParameter);
        }
    
        public virtual int usp_EliminarAnalisis(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarAnalisis", vCodParameter);
        }
    
        public virtual int usp_EliminarEmpresa(string vcodEmpresa)
        {
            var vcodEmpresaParameter = vcodEmpresa != null ?
                new ObjectParameter("VcodEmpresa", vcodEmpresa) :
                new ObjectParameter("VcodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEmpresa", vcodEmpresaParameter);
        }
    
        public virtual int usp_EliminarMedico(string vcodMedico)
        {
            var vcodMedicoParameter = vcodMedico != null ?
                new ObjectParameter("VcodMedico", vcodMedico) :
                new ObjectParameter("VcodMedico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMedico", vcodMedicoParameter);
        }
    
        public virtual int usp_EliminarPaciente(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarPaciente", vCodParameter);
        }
    
        public virtual int usp_EliminarResultado(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarResultado", vCodParameter);
        }
    
        public virtual int usp_InsertarAnalisis(string vDes, Nullable<decimal> vCos, Nullable<int> vEst, string vUsu_Reg)
        {
            var vDesParameter = vDes != null ?
                new ObjectParameter("vDes", vDes) :
                new ObjectParameter("vDes", typeof(string));
    
            var vCosParameter = vCos.HasValue ?
                new ObjectParameter("vCos", vCos) :
                new ObjectParameter("vCos", typeof(decimal));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAnalisis", vDesParameter, vCosParameter, vEstParameter, vUsu_RegParameter);
        }
    
        public virtual int usp_InsertarEmpresa(string vRaz_soc_empl, string vDir_emp, string vTel_emp, string vRuc_emp, string vRep_emp, string vId_ubigeo, Nullable<int> vestado)
        {
            var vRaz_soc_emplParameter = vRaz_soc_empl != null ?
                new ObjectParameter("VRaz_soc_empl", vRaz_soc_empl) :
                new ObjectParameter("VRaz_soc_empl", typeof(string));
    
            var vDir_empParameter = vDir_emp != null ?
                new ObjectParameter("VDir_emp", vDir_emp) :
                new ObjectParameter("VDir_emp", typeof(string));
    
            var vTel_empParameter = vTel_emp != null ?
                new ObjectParameter("VTel_emp", vTel_emp) :
                new ObjectParameter("VTel_emp", typeof(string));
    
            var vRuc_empParameter = vRuc_emp != null ?
                new ObjectParameter("VRuc_emp", vRuc_emp) :
                new ObjectParameter("VRuc_emp", typeof(string));
    
            var vRep_empParameter = vRep_emp != null ?
                new ObjectParameter("VRep_emp", vRep_emp) :
                new ObjectParameter("VRep_emp", typeof(string));
    
            var vId_ubigeoParameter = vId_ubigeo != null ?
                new ObjectParameter("VId_ubigeo", vId_ubigeo) :
                new ObjectParameter("VId_ubigeo", typeof(string));
    
            var vestadoParameter = vestado.HasValue ?
                new ObjectParameter("Vestado", vestado) :
                new ObjectParameter("Vestado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEmpresa", vRaz_soc_emplParameter, vDir_empParameter, vTel_empParameter, vRuc_empParameter, vRep_empParameter, vId_ubigeoParameter, vestadoParameter);
        }
    
        public virtual int usp_InsertarEstadoPaciente(string vNom, string vApe, Nullable<System.DateTime> vFNac, string vDni, Nullable<int> vSexo, string vDir, string vSang, string vEmail, Nullable<System.DateTime> vFIngr, string vTelef, Nullable<int> vEsta, Nullable<int> vTipo, string vCEmpr, string vUsu_Reg, string vId_Ubigeo)
        {
            var vNomParameter = vNom != null ?
                new ObjectParameter("vNom", vNom) :
                new ObjectParameter("vNom", typeof(string));
    
            var vApeParameter = vApe != null ?
                new ObjectParameter("vApe", vApe) :
                new ObjectParameter("vApe", typeof(string));
    
            var vFNacParameter = vFNac.HasValue ?
                new ObjectParameter("vFNac", vFNac) :
                new ObjectParameter("vFNac", typeof(System.DateTime));
    
            var vDniParameter = vDni != null ?
                new ObjectParameter("vDni", vDni) :
                new ObjectParameter("vDni", typeof(string));
    
            var vSexoParameter = vSexo.HasValue ?
                new ObjectParameter("vSexo", vSexo) :
                new ObjectParameter("vSexo", typeof(int));
    
            var vDirParameter = vDir != null ?
                new ObjectParameter("vDir", vDir) :
                new ObjectParameter("vDir", typeof(string));
    
            var vSangParameter = vSang != null ?
                new ObjectParameter("vSang", vSang) :
                new ObjectParameter("vSang", typeof(string));
    
            var vEmailParameter = vEmail != null ?
                new ObjectParameter("vEmail", vEmail) :
                new ObjectParameter("vEmail", typeof(string));
    
            var vFIngrParameter = vFIngr.HasValue ?
                new ObjectParameter("vFIngr", vFIngr) :
                new ObjectParameter("vFIngr", typeof(System.DateTime));
    
            var vTelefParameter = vTelef != null ?
                new ObjectParameter("vTelef", vTelef) :
                new ObjectParameter("vTelef", typeof(string));
    
            var vEstaParameter = vEsta.HasValue ?
                new ObjectParameter("vEsta", vEsta) :
                new ObjectParameter("vEsta", typeof(int));
    
            var vTipoParameter = vTipo.HasValue ?
                new ObjectParameter("vTipo", vTipo) :
                new ObjectParameter("vTipo", typeof(int));
    
            var vCEmprParameter = vCEmpr != null ?
                new ObjectParameter("vCEmpr", vCEmpr) :
                new ObjectParameter("vCEmpr", typeof(string));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEstadoPaciente", vNomParameter, vApeParameter, vFNacParameter, vDniParameter, vSexoParameter, vDirParameter, vSangParameter, vEmailParameter, vFIngrParameter, vTelefParameter, vEstaParameter, vTipoParameter, vCEmprParameter, vUsu_RegParameter, vId_UbigeoParameter);
        }
    
        public virtual int usp_InsertarEvaluacion(Nullable<System.DateTime> vFEva, string vMed, string vAud, Nullable<int> vEst, string vUsu_Reg)
        {
            var vFEvaParameter = vFEva.HasValue ?
                new ObjectParameter("vFEva", vFEva) :
                new ObjectParameter("vFEva", typeof(System.DateTime));
    
            var vMedParameter = vMed != null ?
                new ObjectParameter("vMed", vMed) :
                new ObjectParameter("vMed", typeof(string));
    
            var vAudParameter = vAud != null ?
                new ObjectParameter("vAud", vAud) :
                new ObjectParameter("vAud", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEvaluacion", vFEvaParameter, vMedParameter, vAudParameter, vEstParameter, vUsu_RegParameter);
        }
    
        public virtual int usp_InsertarMedico(string dniMedic, string nomMedico, string apeMedico, string numColegiatura, Nullable<System.DateTime> fechaNacimiento, string emailMedico, string direcMedico, Nullable<int> estado, string codEspecialidad, string login_Usuario, string usu_Registro, string id_Ubigeo, Nullable<System.DateTime> fec_ingreso)
        {
            var dniMedicParameter = dniMedic != null ?
                new ObjectParameter("dniMedic", dniMedic) :
                new ObjectParameter("dniMedic", typeof(string));
    
            var nomMedicoParameter = nomMedico != null ?
                new ObjectParameter("nomMedico", nomMedico) :
                new ObjectParameter("nomMedico", typeof(string));
    
            var apeMedicoParameter = apeMedico != null ?
                new ObjectParameter("apeMedico", apeMedico) :
                new ObjectParameter("apeMedico", typeof(string));
    
            var numColegiaturaParameter = numColegiatura != null ?
                new ObjectParameter("numColegiatura", numColegiatura) :
                new ObjectParameter("numColegiatura", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("fechaNacimiento", fechaNacimiento) :
                new ObjectParameter("fechaNacimiento", typeof(System.DateTime));
    
            var emailMedicoParameter = emailMedico != null ?
                new ObjectParameter("emailMedico", emailMedico) :
                new ObjectParameter("emailMedico", typeof(string));
    
            var direcMedicoParameter = direcMedico != null ?
                new ObjectParameter("direcMedico", direcMedico) :
                new ObjectParameter("direcMedico", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var codEspecialidadParameter = codEspecialidad != null ?
                new ObjectParameter("codEspecialidad", codEspecialidad) :
                new ObjectParameter("codEspecialidad", typeof(string));
    
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var fec_ingresoParameter = fec_ingreso.HasValue ?
                new ObjectParameter("fec_ingreso", fec_ingreso) :
                new ObjectParameter("fec_ingreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMedico", dniMedicParameter, nomMedicoParameter, apeMedicoParameter, numColegiaturaParameter, fechaNacimientoParameter, emailMedicoParameter, direcMedicoParameter, estadoParameter, codEspecialidadParameter, login_UsuarioParameter, usu_RegistroParameter, id_UbigeoParameter, fec_ingresoParameter);
        }
    
        public virtual int usp_InsertarResultado(Nullable<decimal> vPeso, Nullable<decimal> vAltura, string vSangre, string vOrina, string vEkg, string vSpiro, string vPsico, string vXray, string vAudi, string vVisi, string vCodAnal, string vCodEva, string vCodEnfe, string vRecom, string vCodPac, string vUsu_Registro)
        {
            var vPesoParameter = vPeso.HasValue ?
                new ObjectParameter("vPeso", vPeso) :
                new ObjectParameter("vPeso", typeof(decimal));
    
            var vAlturaParameter = vAltura.HasValue ?
                new ObjectParameter("vAltura", vAltura) :
                new ObjectParameter("vAltura", typeof(decimal));
    
            var vSangreParameter = vSangre != null ?
                new ObjectParameter("vSangre", vSangre) :
                new ObjectParameter("vSangre", typeof(string));
    
            var vOrinaParameter = vOrina != null ?
                new ObjectParameter("vOrina", vOrina) :
                new ObjectParameter("vOrina", typeof(string));
    
            var vEkgParameter = vEkg != null ?
                new ObjectParameter("vEkg", vEkg) :
                new ObjectParameter("vEkg", typeof(string));
    
            var vSpiroParameter = vSpiro != null ?
                new ObjectParameter("vSpiro", vSpiro) :
                new ObjectParameter("vSpiro", typeof(string));
    
            var vPsicoParameter = vPsico != null ?
                new ObjectParameter("vPsico", vPsico) :
                new ObjectParameter("vPsico", typeof(string));
    
            var vXrayParameter = vXray != null ?
                new ObjectParameter("vXray", vXray) :
                new ObjectParameter("vXray", typeof(string));
    
            var vAudiParameter = vAudi != null ?
                new ObjectParameter("vAudi", vAudi) :
                new ObjectParameter("vAudi", typeof(string));
    
            var vVisiParameter = vVisi != null ?
                new ObjectParameter("vVisi", vVisi) :
                new ObjectParameter("vVisi", typeof(string));
    
            var vCodAnalParameter = vCodAnal != null ?
                new ObjectParameter("vCodAnal", vCodAnal) :
                new ObjectParameter("vCodAnal", typeof(string));
    
            var vCodEvaParameter = vCodEva != null ?
                new ObjectParameter("vCodEva", vCodEva) :
                new ObjectParameter("vCodEva", typeof(string));
    
            var vCodEnfeParameter = vCodEnfe != null ?
                new ObjectParameter("vCodEnfe", vCodEnfe) :
                new ObjectParameter("vCodEnfe", typeof(string));
    
            var vRecomParameter = vRecom != null ?
                new ObjectParameter("vRecom", vRecom) :
                new ObjectParameter("vRecom", typeof(string));
    
            var vCodPacParameter = vCodPac != null ?
                new ObjectParameter("vCodPac", vCodPac) :
                new ObjectParameter("vCodPac", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarResultado", vPesoParameter, vAlturaParameter, vSangreParameter, vOrinaParameter, vEkgParameter, vSpiroParameter, vPsicoParameter, vXrayParameter, vAudiParameter, vVisiParameter, vCodAnalParameter, vCodEvaParameter, vCodEnfeParameter, vRecomParameter, vCodPacParameter, vUsu_RegistroParameter);
        }
    
        public virtual int usp_InsertarUsuario(string login_Usuario, string pass_Usuario, string usu_Registro)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var pass_UsuarioParameter = pass_Usuario != null ?
                new ObjectParameter("Pass_Usuario", pass_Usuario) :
                new ObjectParameter("Pass_Usuario", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarUsuario", login_UsuarioParameter, pass_UsuarioParameter, usu_RegistroParameter);
        }
    
        public virtual ObjectResult<usp_ListarAnalisis_Result> usp_ListarAnalisis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAnalisis_Result>("usp_ListarAnalisis");
        }
    
        public virtual ObjectResult<usp_ListarAuditor_Result> usp_ListarAuditor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAuditor_Result>("usp_ListarAuditor");
        }
    
        public virtual ObjectResult<usp_ListarEmpresa_Result> usp_ListarEmpresa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEmpresa_Result>("usp_ListarEmpresa");
        }
    
        public virtual ObjectResult<usp_ListarEnfermedad_Result> usp_ListarEnfermedad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEnfermedad_Result>("usp_ListarEnfermedad");
        }
    
        public virtual ObjectResult<usp_ListarEspecialidad_Result> usp_ListarEspecialidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEspecialidad_Result>("usp_ListarEspecialidad");
        }
    
        public virtual ObjectResult<usp_ListarMedico_Result> usp_ListarMedico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMedico_Result>("usp_ListarMedico");
        }
    
        public virtual ObjectResult<usp_ListarMedico2_Result> usp_ListarMedico2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMedico2_Result>("usp_ListarMedico2");
        }
    
        public virtual ObjectResult<usp_ListarPaciente_Result> usp_ListarPaciente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPaciente_Result>("usp_ListarPaciente");
        }
    
        public virtual ObjectResult<usp_ListarPaciente2_Result> usp_ListarPaciente2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPaciente2_Result>("usp_ListarPaciente2");
        }
    
        public virtual ObjectResult<usp_ListarResultados_Result> usp_ListarResultados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarResultados_Result>("usp_ListarResultados");
        }
    
        public virtual ObjectResult<usp_ListarUbicacion_Result> usp_ListarUbicacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUbicacion_Result>("usp_ListarUbicacion");
        }
    
        public virtual ObjectResult<usp_ListarUltAnalisis_Result> usp_ListarUltAnalisis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUltAnalisis_Result>("usp_ListarUltAnalisis");
        }
    
        public virtual ObjectResult<usp_ListarUltEvaluacion_Result> usp_ListarUltEvaluacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUltEvaluacion_Result>("usp_ListarUltEvaluacion");
        }
    }
}
