//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Consultas
    {
        public string codConsulta { get; set; }
        public string codPaciente { get; set; }
        public string codMedico { get; set; }
        public string motivoConsulta { get; set; }
        public Nullable<System.DateTime> fechaConsulta { get; set; }
        public string estado { get; set; }
        public string resultados { get; set; }
    
        public virtual Tb_Medico Tb_Medico { get; set; }
        public virtual Tb_Paciente Tb_Paciente { get; set; }
    }
}
