//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyEspecialidad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspecialidadDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    public partial class EspecialidadDC : object
    {
        
        private string CodEspecialidadField;
        
        private string DescEspecialidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEspecialidad
        {
            get
            {
                return this.CodEspecialidadField;
            }
            set
            {
                this.CodEspecialidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEspecialidad
        {
            get
            {
                return this.DescEspecialidadField;
            }
            set
            {
                this.DescEspecialidadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEspecialidad.IServicioEspecialidad")]
    public interface IServicioEspecialidad
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEspecialidad/usp_ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioEspecialidad/usp_ListarEspecialidadResponse")]
        System.Collections.Generic.List<ProxyEspecialidad.EspecialidadDC> usp_ListarEspecialidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEspecialidad/usp_ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioEspecialidad/usp_ListarEspecialidadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEspecialidad.EspecialidadDC>> usp_ListarEspecialidadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioEspecialidadChannel : ProxyEspecialidad.IServicioEspecialidad, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioEspecialidadClient : System.ServiceModel.ClientBase<ProxyEspecialidad.IServicioEspecialidad>, ProxyEspecialidad.IServicioEspecialidad
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioEspecialidadClient() : 
                base(ServicioEspecialidadClient.GetDefaultBinding(), ServicioEspecialidadClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioEspecialidad.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEspecialidadClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioEspecialidadClient.GetBindingForEndpoint(endpointConfiguration), ServicioEspecialidadClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEspecialidadClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioEspecialidadClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEspecialidadClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioEspecialidadClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioEspecialidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyEspecialidad.EspecialidadDC> usp_ListarEspecialidad()
        {
            return base.Channel.usp_ListarEspecialidad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyEspecialidad.EspecialidadDC>> usp_ListarEspecialidadAsync()
        {
            return base.Channel.usp_ListarEspecialidadAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEspecialidad))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioEspecialidad))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_CheckSalud/ServicioEspecialidad/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioEspecialidadClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioEspecialidad);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioEspecialidadClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioEspecialidad);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioEspecialidad,
        }
    }
}
