//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyEmpresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class EmpresaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecIngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazSocEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirecEmpresa {
            get {
                return this.DirecEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecEmpresaField, value) != true)) {
                    this.DirecEmpresaField = value;
                    this.RaisePropertyChanged("DirecEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Empresa {
            get {
                return this.Est_EmpresaField;
            }
            set {
                if ((this.Est_EmpresaField.Equals(value) != true)) {
                    this.Est_EmpresaField = value;
                    this.RaisePropertyChanged("Est_Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIngreso {
            get {
                return this.FecIngresoField;
            }
            set {
                if ((this.FecIngresoField.Equals(value) != true)) {
                    this.FecIngresoField = value;
                    this.RaisePropertyChanged("FecIngreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazSocEmpresa {
            get {
                return this.RazSocEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.RazSocEmpresaField, value) != true)) {
                    this.RazSocEmpresaField = value;
                    this.RaisePropertyChanged("RazSocEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepEmpresa {
            get {
                return this.RepEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.RepEmpresaField, value) != true)) {
                    this.RepEmpresaField = value;
                    this.RaisePropertyChanged("RepEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RucEmpresa {
            get {
                return this.RucEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.RucEmpresaField, value) != true)) {
                    this.RucEmpresaField = value;
                    this.RaisePropertyChanged("RucEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelEmpresa {
            get {
                return this.TelEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TelEmpresaField, value) != true)) {
                    this.TelEmpresaField = value;
                    this.RaisePropertyChanged("TelEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEmpresa {
            get {
                return this.codEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.codEmpresaField, value) != true)) {
                    this.codEmpresaField = value;
                    this.RaisePropertyChanged("codEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.departamentoField, value) != true)) {
                    this.departamentoField = value;
                    this.RaisePropertyChanged("departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((object.ReferenceEquals(this.distritoField, value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEmpresa.IServicioEmpresa")]
    public interface IServicioEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresaResponse")]
        TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC[] usp_ListarEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ListarEmpresaResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC[]> usp_ListarEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresaResponse")]
        bool usp_InsertarEmpresa(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_InsertarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_InsertarEmpresaAsync(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresaResponse")]
        bool usp_ActualizarEmpresa(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ActualizarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_ActualizarEmpresaAsync(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresaResponse")]
        bool usp_EliminarEmpresa(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_EliminarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> usp_EliminarEmpresaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresaResponse")]
        TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC usp_ConsultarEmpresa(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ConsultarEmpresaResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC> usp_ConsultarEmpresaAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ExisteRuc", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ExisteRucResponse")]
        bool usp_ExisteRuc(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/usp_ExisteRuc", ReplyAction="http://tempuri.org/IServicioEmpresa/usp_ExisteRucResponse")]
        System.Threading.Tasks.Task<bool> usp_ExisteRucAsync(string ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpresaChannel : TestWeb_WCF_CheckSalud.ProxyEmpresa.IServicioEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpresaClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyEmpresa.IServicioEmpresa>, TestWeb_WCF_CheckSalud.ProxyEmpresa.IServicioEmpresa {
        
        public ServicioEmpresaClient() {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC[] usp_ListarEmpresa() {
            return base.Channel.usp_ListarEmpresa();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC[]> usp_ListarEmpresaAsync() {
            return base.Channel.usp_ListarEmpresaAsync();
        }
        
        public bool usp_InsertarEmpresa(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC) {
            return base.Channel.usp_InsertarEmpresa(objEmpresaDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_InsertarEmpresaAsync(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC) {
            return base.Channel.usp_InsertarEmpresaAsync(objEmpresaDC);
        }
        
        public bool usp_ActualizarEmpresa(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC) {
            return base.Channel.usp_ActualizarEmpresa(objEmpresaDC);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ActualizarEmpresaAsync(TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC objEmpresaDC) {
            return base.Channel.usp_ActualizarEmpresaAsync(objEmpresaDC);
        }
        
        public bool usp_EliminarEmpresa(string strCodigo) {
            return base.Channel.usp_EliminarEmpresa(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> usp_EliminarEmpresaAsync(string strCodigo) {
            return base.Channel.usp_EliminarEmpresaAsync(strCodigo);
        }
        
        public TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC usp_ConsultarEmpresa(string strCodigo) {
            return base.Channel.usp_ConsultarEmpresa(strCodigo);
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEmpresa.EmpresaDC> usp_ConsultarEmpresaAsync(string strCodigo) {
            return base.Channel.usp_ConsultarEmpresaAsync(strCodigo);
        }
        
        public bool usp_ExisteRuc(string ruc) {
            return base.Channel.usp_ExisteRuc(ruc);
        }
        
        public System.Threading.Tasks.Task<bool> usp_ExisteRucAsync(string ruc) {
            return base.Channel.usp_ExisteRucAsync(ruc);
        }
    }
}
