//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyResultado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class ResultadoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EvaluadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomApePacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float alturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string audicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEnfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ekgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lugarTrabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float pesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psicologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rayosXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recomendacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sangreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spirometriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoExamenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evaluador {
            get {
                return this.EvaluadorField;
            }
            set {
                if ((object.ReferenceEquals(this.EvaluadorField, value) != true)) {
                    this.EvaluadorField = value;
                    this.RaisePropertyChanged("Evaluador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomApePaciente {
            get {
                return this.NomApePacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomApePacienteField, value) != true)) {
                    this.NomApePacienteField = value;
                    this.RaisePropertyChanged("NomApePaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float altura {
            get {
                return this.alturaField;
            }
            set {
                if ((this.alturaField.Equals(value) != true)) {
                    this.alturaField = value;
                    this.RaisePropertyChanged("altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string audicion {
            get {
                return this.audicionField;
            }
            set {
                if ((object.ReferenceEquals(this.audicionField, value) != true)) {
                    this.audicionField = value;
                    this.RaisePropertyChanged("audicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAnalisis {
            get {
                return this.codAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.codAnalisisField, value) != true)) {
                    this.codAnalisisField = value;
                    this.RaisePropertyChanged("codAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEnfermedad {
            get {
                return this.codEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.codEnfermedadField, value) != true)) {
                    this.codEnfermedadField = value;
                    this.RaisePropertyChanged("codEnfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEvaluacion {
            get {
                return this.codEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codEvaluacionField, value) != true)) {
                    this.codEvaluacionField = value;
                    this.RaisePropertyChanged("codEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPaciente {
            get {
                return this.codPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codPacienteField, value) != true)) {
                    this.codPacienteField = value;
                    this.RaisePropertyChanged("codPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codResultado {
            get {
                return this.codResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.codResultadoField, value) != true)) {
                    this.codResultadoField = value;
                    this.RaisePropertyChanged("codResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ekg {
            get {
                return this.ekgField;
            }
            set {
                if ((object.ReferenceEquals(this.ekgField, value) != true)) {
                    this.ekgField = value;
                    this.RaisePropertyChanged("ekg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enfermedad {
            get {
                return this.enfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.enfermedadField, value) != true)) {
                    this.enfermedadField = value;
                    this.RaisePropertyChanged("enfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecNac {
            get {
                return this.fecNacField;
            }
            set {
                if ((this.fecNacField.Equals(value) != true)) {
                    this.fecNacField = value;
                    this.RaisePropertyChanged("fecNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaEvaluacion {
            get {
                return this.fechaEvaluacionField;
            }
            set {
                if ((this.fechaEvaluacionField.Equals(value) != true)) {
                    this.fechaEvaluacionField = value;
                    this.RaisePropertyChanged("fechaEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lugarTrabajo {
            get {
                return this.lugarTrabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.lugarTrabajoField, value) != true)) {
                    this.lugarTrabajoField = value;
                    this.RaisePropertyChanged("lugarTrabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orina {
            get {
                return this.orinaField;
            }
            set {
                if ((object.ReferenceEquals(this.orinaField, value) != true)) {
                    this.orinaField = value;
                    this.RaisePropertyChanged("orina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float peso {
            get {
                return this.pesoField;
            }
            set {
                if ((this.pesoField.Equals(value) != true)) {
                    this.pesoField = value;
                    this.RaisePropertyChanged("peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psicologia {
            get {
                return this.psicologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.psicologiaField, value) != true)) {
                    this.psicologiaField = value;
                    this.RaisePropertyChanged("psicologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rayosX {
            get {
                return this.rayosXField;
            }
            set {
                if ((object.ReferenceEquals(this.rayosXField, value) != true)) {
                    this.rayosXField = value;
                    this.RaisePropertyChanged("rayosX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recomendaciones {
            get {
                return this.recomendacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.recomendacionesField, value) != true)) {
                    this.recomendacionesField = value;
                    this.RaisePropertyChanged("recomendaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sangre {
            get {
                return this.sangreField;
            }
            set {
                if ((object.ReferenceEquals(this.sangreField, value) != true)) {
                    this.sangreField = value;
                    this.RaisePropertyChanged("sangre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spirometria {
            get {
                return this.spirometriaField;
            }
            set {
                if ((object.ReferenceEquals(this.spirometriaField, value) != true)) {
                    this.spirometriaField = value;
                    this.RaisePropertyChanged("spirometria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoExamen {
            get {
                return this.tipoExamenField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoExamenField, value) != true)) {
                    this.tipoExamenField = value;
                    this.RaisePropertyChanged("tipoExamen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vista {
            get {
                return this.vistaField;
            }
            set {
                if ((object.ReferenceEquals(this.vistaField, value) != true)) {
                    this.vistaField = value;
                    this.RaisePropertyChanged("vista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyResultado.IServicioResultado")]
    public interface IServicioResultado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ConsultarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ConsultarResultadoResponse")]
        TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC ConsultarResultado(string codResultado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ConsultarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ConsultarResultadoResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC> ConsultarResultadoAsync(string codResultado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ListarResultadoResponse")]
        TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC[] ListarResultado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ListarResultadoResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC[]> ListarResultadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/InsertarResultado", ReplyAction="http://tempuri.org/IServicioResultado/InsertarResultadoResponse")]
        bool InsertarResultado(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/InsertarResultado", ReplyAction="http://tempuri.org/IServicioResultado/InsertarResultadoResponse")]
        System.Threading.Tasks.Task<bool> InsertarResultadoAsync(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ActualizarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ActualizarResultadoResponse")]
        bool ActualizarResultado(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ActualizarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ActualizarResultadoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarResultadoAsync(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/EliminarResultado", ReplyAction="http://tempuri.org/IServicioResultado/EliminarResultadoResponse")]
        bool EliminarResultado(string codResultado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/EliminarResultado", ReplyAction="http://tempuri.org/IServicioResultado/EliminarResultadoResponse")]
        System.Threading.Tasks.Task<bool> EliminarResultadoAsync(string codResultado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResultadoChannel : TestWeb_WCF_CheckSalud.ProxyResultado.IServicioResultado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResultadoClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyResultado.IServicioResultado>, TestWeb_WCF_CheckSalud.ProxyResultado.IServicioResultado {
        
        public ServicioResultadoClient() {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC ConsultarResultado(string codResultado) {
            return base.Channel.ConsultarResultado(codResultado);
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC> ConsultarResultadoAsync(string codResultado) {
            return base.Channel.ConsultarResultadoAsync(codResultado);
        }
        
        public TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC[] ListarResultado() {
            return base.Channel.ListarResultado();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC[]> ListarResultadoAsync() {
            return base.Channel.ListarResultadoAsync();
        }
        
        public bool InsertarResultado(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.InsertarResultado(objResultadoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarResultadoAsync(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.InsertarResultadoAsync(objResultadoDC);
        }
        
        public bool ActualizarResultado(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.ActualizarResultado(objResultadoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarResultadoAsync(TestWeb_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.ActualizarResultadoAsync(objResultadoDC);
        }
        
        public bool EliminarResultado(string codResultado) {
            return base.Channel.EliminarResultado(codResultado);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarResultadoAsync(string codResultado) {
            return base.Channel.EliminarResultadoAsync(codResultado);
        }
    }
}
