//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyEvaluacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EvaluacionDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class EvaluacionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_EvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaEvaluacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_Evaluacion {
            get {
                return this.Est_EvaluacionField;
            }
            set {
                if ((this.Est_EvaluacionField.Equals(value) != true)) {
                    this.Est_EvaluacionField = value;
                    this.RaisePropertyChanged("Est_Evaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAuditor {
            get {
                return this.codAuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.codAuditorField, value) != true)) {
                    this.codAuditorField = value;
                    this.RaisePropertyChanged("codAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEvaluacion {
            get {
                return this.codEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codEvaluacionField, value) != true)) {
                    this.codEvaluacionField = value;
                    this.RaisePropertyChanged("codEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codMedico {
            get {
                return this.codMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.codMedicoField, value) != true)) {
                    this.codMedicoField = value;
                    this.RaisePropertyChanged("codMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaEvaluacion {
            get {
                return this.fechaEvaluacionField;
            }
            set {
                if ((this.fechaEvaluacionField.Equals(value) != true)) {
                    this.fechaEvaluacionField = value;
                    this.RaisePropertyChanged("fechaEvaluacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEvaluacion.IServicioEvaluacion")]
    public interface IServicioEvaluacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacionResponse")]
        bool InsertarEvaluacion(TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacionResponse")]
        System.Threading.Tasks.Task<bool> InsertarEvaluacionAsync(TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ConsultarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ConsultarEvaluacionResponse")]
        TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC ConsultarEvaluacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ConsultarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ConsultarEvaluacionResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC> ConsultarEvaluacionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEvaluacionChannel : TestWeb_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEvaluacionClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion>, TestWeb_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion {
        
        public ServicioEvaluacionClient() {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEvaluacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarEvaluacion(TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC) {
            return base.Channel.InsertarEvaluacion(objEvaluacionDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEvaluacionAsync(TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC) {
            return base.Channel.InsertarEvaluacionAsync(objEvaluacionDC);
        }
        
        public TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC ConsultarEvaluacion() {
            return base.Channel.ConsultarEvaluacion();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC> ConsultarEvaluacionAsync() {
            return base.Channel.ConsultarEvaluacionAsync();
        }
    }
}
