//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb_WCF_CheckSalud.ProxyAuditor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuditorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class AuditorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAuditorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Auditor {
            get {
                return this.AuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditorField, value) != true)) {
                    this.AuditorField = value;
                    this.RaisePropertyChanged("Auditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAuditor {
            get {
                return this.codAuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.codAuditorField, value) != true)) {
                    this.codAuditorField = value;
                    this.RaisePropertyChanged("codAuditor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAuditor.IServicioAuditor")]
    public interface IServicioAuditor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuditor/ListarAuditor", ReplyAction="http://tempuri.org/IServicioAuditor/ListarAuditorResponse")]
        TestWeb_WCF_CheckSalud.ProxyAuditor.AuditorDC[] ListarAuditor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAuditor/ListarAuditor", ReplyAction="http://tempuri.org/IServicioAuditor/ListarAuditorResponse")]
        System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyAuditor.AuditorDC[]> ListarAuditorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAuditorChannel : TestWeb_WCF_CheckSalud.ProxyAuditor.IServicioAuditor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAuditorClient : System.ServiceModel.ClientBase<TestWeb_WCF_CheckSalud.ProxyAuditor.IServicioAuditor>, TestWeb_WCF_CheckSalud.ProxyAuditor.IServicioAuditor {
        
        public ServicioAuditorClient() {
        }
        
        public ServicioAuditorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAuditorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAuditorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAuditorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWeb_WCF_CheckSalud.ProxyAuditor.AuditorDC[] ListarAuditor() {
            return base.Channel.ListarAuditor();
        }
        
        public System.Threading.Tasks.Task<TestWeb_WCF_CheckSalud.ProxyAuditor.AuditorDC[]> ListarAuditorAsync() {
            return base.Channel.ListarAuditorAsync();
        }
    }
}
